name: baseline_features

data:
  index_path: data/indice.xlsx
  masks_dir: data/conjunto-de-mascaras
  file_name_column: Nome do arquivo
  farm_column: Fazenda
  target_column: Peso
  tag_column: Tags

output:
  features_index_path: generated/baseline_features.csv
  columns:
    - file_name
    - farm
    - weight
    - tag
    - area
    - perimeter
    - solidity
    - circularity
    - equivalent_diameter
    - hu_moment_1
    - hu_moment_2
